import = [
    # "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    "~/.config/alacritty/themes/themes/hyper.toml"
]

[font]
# normal = { family = "BlexMono Nerd Font" }
# normal = { family = "DejaVuSansM Nerd Font Mono" }
# normal = { family = "Iosevka Nerd Font Mono" }
normal = { family = "FantasqueSansM Nerd Font Mono", style = "Regular" }

size = 16

[colors.primary]
background = "#121212"
